# Generated by Django 4.2.6 on 2024-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sloc', models.CharField(max_length=100)),
                ('snum', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('simg', models.ImageField(upload_to='')),
            ],
        ),
    ]
