# Generated by Django 4.2.6 on 2024-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
