# Generated by Django 4.2.6 on 2024-04-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bAutor', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.CharField(max_length=100)),
                ('sMarks', models.IntegerField()),
                ('bName', models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='smarks',
            field=models.IntegerField(default=35),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=100)),
                ('tSub', models.CharField(max_length=100)),
                ('subName', models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='app.subjacts')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='tName',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
