# Generated by Django 4.2.6 on 2024-04-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_subjacts_student_smarks_teacher_student_tname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='subjacts',
            name='bName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjacts'),
        ),
    ]
